name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-266.0.dev <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.3
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/
